server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
          - path=/department/**
          
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - path=/users/**
          
                                        
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost 